import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto p-8 space-y-6 text-gray-800 dark:text-gray-200">
      <Link href="/dashboard" className="text-blue-600 dark:text-blue-400 text-sm hover:underline">
        &larr; Back to Dashboard
      </Link>
      <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Terms of Service</h1>
      <p className="text-sm text-gray-500">Last updated: September 2026</p>

      <div className="space-y-4 text-sm leading-relaxed">
        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">1. Acceptance of Terms</h2>
        <p>
          By accessing or using TikTok Coach AI, you agree to be bound by these Terms of Service.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">2. AI Recommendations Disclaimer</h2>
        <p>
          The analytics and strategies provided by TikTok Coach AI are generated by artificial intelligence. We do not guarantee specific follower growth, view counts, or viral reach.
        </p>

        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">3. Acceptable Use</h2>
        <p>
          You agree not to misuse our API endpoints or attempt automated extraction against system stability.
        </p>
      </div>
    </div>
  );
}
